// Re-exportando tipos do pacote shared relacionados a projeto e tarefas
export type {
  Project,
  Team,
  UserTeam,
  TeamProject,
  StatusFlow,
  Status,
  Epic,
  UserStory,
  Task,
  TaskAssignment,
  Sprint,
  SprintBacklogItem,
  Comment,
  Activity,
  Session,
  ProjectSetting,
  SprintMetric,
  ProjectLabel,
  TaskLabel,
  TaskAttachment,
  TaskDependency,
  CreateProjectDTO,
  UpdateProjectDTO,
  CreateTeamDTO,
  UpdateTeamDTO,
  CreateEpicDTO,
  UpdateEpicDTO,
  CreateUserStoryDTO,
  UpdateUserStoryDTO,
  CreateTaskDTO,
  UpdateTaskDTO,
  CreateSprintDTO,
  UpdateSprintDTO,
  CreateCommentDTO,
  UpdateCommentDTO,
  ApiResponse,
  CreateProjectInput,
  UpdateProjectInput,
  ProjectIdInput,
  ProjectSlugInput,
  CreateTeamInput,
  UpdateTeamInput,
  TeamIdInput,
  CreateEpicInput,
  UpdateEpicInput,
  EpicIdInput,
  CreateUserStoryInput,
  UpdateUserStoryInput,
  UserStoryIdInput,
  CreateTaskInput,
  UpdateTaskInput,
  TaskIdInput,
  CreateSprintInput,
  UpdateSprintInput,
  SprintIdInput,
  CreateCommentInput,
  UpdateCommentInput,
  CommentIdInput,
} from "@packages/shared";

import { Task } from "@shared";

export type { Task };
